version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./web-app/backend
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/ai-pbt
      - JWT_SECRET=change-me
      - ENCRYPTION_KEY_BASE64=ZmFrZS1kZXYta2V5LWZha2UtZGV2LWtleS1mYWtlZGV2a2V5
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  frontend:
    build: ./web-app/frontend
    environment:
      - VITE_API_BASE=http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  mongo_data: {}